<a href="https://colab.research.google.com/github/UmaEdiga04/DL-lab/blob/main/mul_2_mat_using_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

matrix_size = 3
batch_size = 64
epochs = 10

def generate_data(samples, size):
    A = np.random.rand(samples, size, size)
    B = np.random.rand(samples, size, size)
    C = np.array([np.matmul(a, b) for a, b in zip(A, B)])
    return (A, B), C

(X_train_A, X_train_B), Y_train = generate_data(1000, matrix_size)
(X_test_A, X_test_B), Y_test = generate_data(200, matrix_size)

model = Sequential([
    Flatten(input_shape=(matrix_size, matrix_size)),
    Dense(matrix_size * matrix_size, activation='relu'),
    Densemodel.compile(optimizer=Adam(learning_rate=0.001),
              loss='mean_squared_error',
              metrics=['accuracy'])

model.fit(np.concatenate([X_train_A, X_train_B], axis=-1), Y_train.flatten(),
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.2)

loss, accuracy = model.evaluate(np.concatenate([X_test_A, X_test_B], axis=-1), Y_test.flatten())
print(f'Loss: {loss}, Accuracy: {accuracy}')

predictions = model.predict(np.concatenate([X_test_A, X_test_B], axis=-1))

for i in range(5):
    print(f"Predicted:\n{predictions[i].reshape(matrix_size, matrix_size)}")
    print(f"Actual:\n{Y_test[i]}")


Epoch 1/10


ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_18" is incompatible with the layer: expected axis -1 of input shape to have value 9, but received input with shape (None, 18)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(None, 3, 6), dtype=float32)
  • training=True
  • mask=None

In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
from tensorflow.keras.optimizers import Adam

matrix_size = 3
batch_size = 64
epochs = 10

def generate_data(samples, size):
    A = np.random.rand(samples, size, size)
    B = np.random.rand(samples, size, size)
    C = np.array([np.matmul(a, b) for a, b in zip(A, B)])
    return (A, B), C

(X_train_A, X_train_B), Y_train = generate_data(1000, matrix_size)
(X_test_A, X_test_B), Y_test = generate_data(200, matrix_size)

model = Sequential([
    Flatten(input_shape=(matrix_size, matrix_size)),
    Dense(matrix_size * matrix_size, activation='relu'),
    Dense(matrix_size * matrix_size)
])

model.compile(optimizer=Adam(learning_rate=0.001),
              loss='mean_squared_error',
              metrics=['accuracy'])

model.fit(np.concatenate([X_train_A, X_train_B], axis=-1), Y_train.flatten(),
          batch_size=batch_size,
          epochs=epochs,
          validation_split=0.2)

loss, accuracy = model.evaluate(np.concatenate([X_test_A, X_test_B], axis=-1), Y_test.flatten())
print(f'Loss: {loss}, Accuracy: {accuracy}')

predictions = model.predict(np.concatenate([X_test_A, X_test_B], axis=-1))
for i in range(5):
    print(f"Predicted:\n{predictions[i].reshape(matrix_size, matrix_size)}")
    print(f"Actual:\n{Y_test[i]}")


Epoch 1/10


/usr/local/lib/python3.10/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


ValueError: Exception encountered when calling Sequential.call().

Input 0 of layer "dense_22" is incompatible with the layer: expected axis -1 of input shape to have value 9, but received input with shape (None, 18)

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=(None, 3, 6), dtype=float32)
  • training=True
  • mask=None

In [14]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

A = np.random.rand(2, 3)
B = np.random.rand(3, 4)

model = Sequential()
model.add(Dense(4, input_shape=(2, 3)))

model.compile(optimizer='adam', loss='mean_squared_error')

X = np.array([A])
y = np.dot(A, B)

model.fit(X, y, epochs=1000, verbose=0)

result = model.predict(X)
print("Result:")
print(result)

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


ValueError: Data cardinality is ambiguous. Make sure all arrays contain the same number of samples.'x' sizes: 1
'y' sizes: 2


In [15]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Reshape, Flatten
from keras.layers import Input
from keras.models import Model

# Define the matrices to be multiplied
A = np.random.rand(1, 2, 3)
B = np.random.rand(1, 3, 4)

# Define the input shape
input_A = Input(shape=(2, 3))
input_B = Input(shape=(3, 4))

# Flatten the input matrices
flat_A = Flatten()(input_A)
flat_B = Flatten()(input_B)

# Concatenate the flattened matrices
concat = np.concatenate((flat_A, flat_B), axis=-1)

# Define the model
x = Dense(24, activation='relu')(concat)
x = Reshape((2, 4))(x)

# Define the model
model = Model(inputs=[input_A, input_B], outputs=x)

# Compile the model
model.compile(optimizer='adam', loss='mean_squared_error')

# Define the output data
y = np.dot(A[0], B[0])

# Train the model
model.fit([A, B], np.expand_dims(y, axis=0), epochs=1000, verbose=0)

# Evaluate the model
result = model.predict([A, B])
print("Result:")
print(result)

ValueError: A KerasTensor is symbolic: it's a placeholder for a shape an a dtype. It doesn't have any actual numerical value. You cannot convert it to a NumPy array.

In [17]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

def generate_primes(limit):
    primes = []
    for num in range(2, limit + 1):
        is_prime = True
        for i in range(2, int(np.sqrt(num)) + 1):
            if num % i == 0:
                is_prime = False
                break
        if is_prime:
            primes.append(num)
    return primes

primes = generate_primes(1000)

numbers = np.arange(2, 1001)
labels = np.array([1 if num in primes else 0 for num in numbers])

train_numbers, test_numbers, train_labels, test_labels = train_test_split(numbers, labels, test_size=0.2, random_state=42)

model = Sequential()
model.add(Dense(64, activation='relu', input_shape=(1,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

model.fit(train_numbers, train_labels, epochs=100, batch_size=128, validation_data=(test_numbers, test_labels))

loss, accuracy = model.evaluate(test_numbers, test_labels)
print(f'Test accuracy: {accuracy:.2f}')

def predict_primes(model, limit):
    numbers = np.arange(2, limit + 1)
    predictions = model.predict(numbers)
    primes = [num for num, pred in zip(numbers, predictions) if pred > 0.5]
    return primes

predicted_primes = predict_primes(model, 1000)
print(predicted_primes)

NameError: name 'train_test_split' is not defined

In [19]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

max_num = 1000
batch_size = 32
epochs = 10

def is_prime(n):
    if n <= 1:
        return False
    if n <= 3:
        return True
    if n % 2 == 0 or n % 3 == 0:
        return False
    i = 5
    while i * i <= n:
        if n % i == 0 or n % (i + 2) == 0:
            return False
        i += 6
    return True

def generate_data(max_num):
    X = np.arange(max_num)
    y = np.array([1 if is_prime(x) else 0 for x in X])
    return X, y

X_train, y_train = generate_data(max_num)

model = Sequential([
    Dense(64, input_dim=1, activation='relu'),
    Dense(64, activation='relu'),
    Dense(1, activation='sigmoid')
])

model.compile(optimizer=Adam(learning_rate=0.001),
              loss='binary_crossentropy',
              metrics=['accuracy'])

model.fit(X_train, y_train,
          batch_size=batch_size,
          epochs=epochs)

loss, accuracy = model.evaluate(X_train, y_train)
print(f'Loss: {loss}, Accuracy: {accuracy}')

predictions = model.predict(X_train)
predicted_primes = [i for i in X_train if predictions[i][0] > 0.5]

print(f"Predicted prime numbers: {predicted_primes}")


Epoch 1/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.3969 - loss: 45.4942 
Epoch 2/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7939 - loss: 4.9330 
Epoch 3/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.7342 - loss: 0.9170 
Epoch 4/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.7253 - loss: 0.7366 
Epoch 5/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8351 - loss: 0.5265 
Epoch 6/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8304 - loss: 0.5130 
Epoch 7/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8292 - loss: 0.5040 
Epoch 8/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8448 - loss: 0.4719 
Epoch 9/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8303 - loss: 0.5788 
Epoch 10/10
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8333 - loss: 0.4933 
32/32 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8014 - loss: 0.5312  
Loss: 0.5486884117126465, Accuracy: 0.8320000171661377
32/32 ━━━━━━━━━━━━

In [20]:
import numpy as np
from keras.models import Model
from keras.layers import Input, Dense, Flatten, Reshape
from keras.optimizers import Adam

# Define the input shapes
input_shape_A = (3, 4)  # Matrix A shape
input_shape_B = (4, 5)  # Matrix B shape

# Define the output shape
output_shape = (3, 5)  # Resultant matrix shape

# Define the input layers
input_A = Input(shape=input_shape_A)
input_B = Input(shape=input_shape_B)

# Flatten the input matrices
flat_A = Flatten()(input_A)
flat_B = Flatten()(input_B)

# Concatenate the flattened matrices
concat = np.concatenate((flat_A, flat_B), axis=-1)

# Define the model
x = Dense(64, activation='relu')(concat)
x = Dense(64, activation='relu')(x)
x = Dense(np.prod(output_shape), activation='linear')(x)
x = Reshape(output_shape)(x)

# Define the model
model = Model(inputs=[input_A, input_B], outputs=x)

# Compile the model
model.compile(optimizer=Adam(lr=0.001), loss='mean_squared_error')

# Generate random matrices for training
num_samples = 1000
A_train = np.random.rand(num_samples, *input_shape_A)
B_train = np.random.rand(num_samples, *input_shape_B)
C_train = np.matmul(A_train, B_train)

# Train the model
model.fit([A_train, B_train], C_train, epochs=100, batch_size=32, verbose=2)

# Evaluate the model
A_test = np.random.rand(1, *input_shape_A)
B_test = np.random.rand(1, *input_shape_B)
C_pred = model.predict([A_test, B_test])

# Print the result
print("Matrix A:")
print(A_test[0])
print("Matrix B:")
print(B_test[0])
print("Resultant Matrix:")
print(C_pred[0])

ValueError: A KerasTensor is symbolic: it's a placeholder for a shape an a dtype. It doesn't have any actual numerical value. You cannot convert it to a NumPy array.

In [24]:
import numpy as np
from keras.models import Model
from keras.layers import Input, Dense, Flatten, Reshape
from keras.optimizers import Adam

# Define the input shapes
input_shape_A = (3, 4)  # Matrix A shape
input_shape_B = (4, 5)  # Matrix B shape

# Define the output shape
output_shape = (3, 5)  # Resultant matrix shape

# Define the input layers
input_A = Input(shape=input_shape_A)
input_B = Input(shape=input_shape_B)

# Define the model
x = Dense(np.prod(output_shape), activation='linear')(input_A)

# Generate random matrices for training
num_samples = 1000
A_train = np.random.rand(num_samples, *input_shape_A)
B_train = np.random.rand(num_samples, *input_shape_B)
C_train = np.matmul(A_train, B_train)

# Evaluate the model
A_test = np.random.rand(1, *input_shape_A)
B_test = np.random.rand(1, *input_shape_B)
C_pred = model.predict(A_test)

# Print the result
print("Matrix A:")
print(A_test[0])
print("Matrix B:")
print(B_test[0])
print("Resultant Matrix (predicted):")
print(C_pred[0])
print("Resultant Matrix (actual):")
print(np.matmul(A_test[0], B_test[0]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step
Matrix A:
[[0.60799179 0.9893149  0.03331032 0.23020574]
 [0.11459062 0.02106655 0.9997522  0.98122024]
 [0.07909206 0.30704259 0.73224596 0.6229007 ]]
Matrix B:
[[0.17466274 0.35391243 0.61224988 0.7072801  0.06806321]
 [0.94932135 0.97956794 0.85390785 0.40534844 0.21084469]
 [0.96681778 0.76102053 0.02824301 0.82123818 0.11984685]
 [0.00114914 0.57339943 0.83829666 0.25117995 0.8002708 ]]
Resultant Matrix (predicted):
[[ 0.26122537 -0.45557505 -0.28204983  0.08369577 -0.34528577 -0.46730077
  -0.0136008   0.5437227  -0.24089977  0.00782267 -0.01072645 -0.99600184
   0.1566619   0.18355283  0.6705991 ]
 [ 0.14369968  0.10859174  0.18014613  0.13806257  0.7219987   0.55926245
   0.7783314  -0.19072802 -0.32808304 -0.19033405  0.9972398  -0.98005474
  -0.6484873  -0.57795906 -0.3830039 ]
 [ 0.09072261  0.06457394  0.13985951  0.14379036  0.3656132   0.26790038
   0.3963176  -0.01337622 -0.25917646 -0.14335798  0.68391156 -0.8260264
  -0.44888398 -0